name: Compile Examples

on:
  pull_request:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "examples/**"
      - "src/**"
  push:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "examples/**"
      - "src/**"
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest

    env:
      SKETCHES_REPORTS_PATH: sketches-reports
      # Libraries to install for all boards
      UNIVERSAL_LIBRARIES: |
        # Install the Artim library from the local path
        - source-path: ./
        - name: Artim
      UNIVERSAL_SKETCH_PATHS: |
        - examples
    strategy:
      fail-fast: false

      matrix:
        board: [
          {"fqbn": "esp8266:esp8266:nodemcuv2", "type": "esp8266"},
          {"fqbn": "arduino:avr:uno", "type": "avr"}
        ]
        # make board type-specific customizations to the matrix jobs
        include:
          # ESP8266 boards
          - board:
              type: "esp8266"
            platforms: |
              # Install ESP8266 platform via Boards Manager
              - name: esp8266:esp8266
                source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
            libraries:
            sketch-paths:

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile examples
        #uses: arduino/actions/libraries/compile-examples@master
        uses: arduino/compile-sketches@main
        with:
          platforms: ${{ matrix.platforms }}
          fqbn: ${{ matrix.board.fqbn }}
          #libraries: |
          #  ${{ env.UNIVERSAL_LIBRARIES }}
          #sketch-paths: |
          #  ${{ env.UNIVERSAL_SKETCH_PATHS }}
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Save memory usage change report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.SKETCHES_REPORTS_PATH }}
          path: ${{ env.SKETCHES_REPORTS_PATH }}
